[package]
name = "crypto-rs"
version = "0.1.0"
authors = ["p.classen <p.classen@otterbach.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]